name: CI

on:
    pull_request: ~
    push:
        branches:
            - master
            - v1.x
jobs:
    ci:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [ '8.0' ]
                include:
                  - php: '8.1'
                    experimental: true
                    composer-options: "--ignore-platform-reqs"

        name: PHP ${{ matrix.php }}

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}

            -   uses: "ramsey/composer-install@v1"
                with:
                    composer-options: ${{ matrix.composer-options }}

            - name: setup yarn for frontend assets
              run: |
                curl -o- -L https://yarnpkg.com/install.sh | sudo bash
                yarn install
                yarn run build

            -   name: Linting PHP
                run: make lint-php
                continue-on-error: ${{ matrix.experimental }}

            -   name: PHPCS Code Style Check
                run: make check-cs
                continue-on-error: ${{ matrix.experimental }}

            -   name: PHPStan Static Analyses
                run: make static-analysis
                continue-on-error: ${{ matrix.experimental }}

            -   name: Unit Tests
                run: make phpunit
                continue-on-error: ${{ matrix.experimental }}

            -   name: Behat Feature Tests
                run: make feature-tests
                continue-on-error: ${{ matrix.experimental }}
